// <auto-generated />
using System;
using Consulcon.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consulcon.Infrastructure.Migrations
{
    [DbContext(typeof(ConsulconDbContext))]
    [Migration("20260228031946_AddSaldoAFavorToPropiedad")]
    partial class AddSaldoAFavorToPropiedad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConfigContableServicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<int>("IdCuentaIngreso")
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta_ingreso");

                    b.HasKey("IdServicio", "IdCuentaIngreso")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdCuentaIngreso" }, "fk_ccs_cuenta");

                    b.ToTable("config_contable_servicio", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Comunicacion.ComunicadoBlog", b =>
                {
                    b.Property<int>("IdBlog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_blog");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBlog"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("ContenidoHtml")
                        .HasColumnType("text")
                        .HasColumnName("contenido_html");

                    b.Property<DateTime?>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_publicacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdCondominio")
                        .HasColumnType("int")
                        .HasColumnName("id_condominio");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlArchivoAdjunto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_archivo_adjunto");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_imagen");

                    b.HasKey("IdBlog")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCondominio" }, "fk_blog_condominio");

                    b.ToTable("comunicado_blog", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AccountDailyBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("BancoIdBanco")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdBanco")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BancoIdBanco");

                    b.ToTable("AccountDailyBalances");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AccountTransactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("AccountTransactionHistory", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AsientoContable", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asiento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsiento"));

                    b.Property<DateTime>("FechaContable")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_contable");

                    b.Property<string>("GlosaGeneral")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("glosa_general");

                    b.Property<int>("IdCondominio")
                        .HasColumnType("int")
                        .HasColumnName("id_condominio");

                    b.Property<int?>("IdTransaccionOrigenEgreso")
                        .HasColumnType("int")
                        .HasColumnName("id_transaccion_origen_egreso")
                        .HasComment("Link a Tesoreria");

                    b.Property<int?>("IdTransaccionOrigenPago")
                        .HasColumnType("int")
                        .HasColumnName("id_transaccion_origen_pago")
                        .HasComment("Link a Tesoreria");

                    b.Property<string>("NroDocumentoRespaldo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nro_documento_respaldo");

                    b.Property<string>("TipoAsiento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_asiento")
                        .HasComment("Diario, Ajuste, Cierre");

                    b.HasKey("IdAsiento")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCondominio" }, "fk_asiento_condominio");

                    b.HasIndex(new[] { "IdTransaccionOrigenEgreso" }, "fk_asiento_egreso");

                    b.HasIndex(new[] { "IdTransaccionOrigenPago" }, "fk_asiento_pago");

                    b.ToTable("asiento_contable", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AsientoDetalle", b =>
                {
                    b.Property<int>("IdAsientoDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asiento_det");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsientoDet"));

                    b.Property<decimal?>("Debe")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("debe")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("GlosaLinea")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("glosa_linea");

                    b.Property<decimal?>("Haber")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("haber")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int>("IdAsiento")
                        .HasColumnType("int")
                        .HasColumnName("id_asiento");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta");

                    b.HasKey("IdAsientoDet")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAsiento" }, "fk_ad_asiento");

                    b.HasIndex(new[] { "IdCuenta" }, "fk_ad_cuenta");

                    b.ToTable("asiento_detalle", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AutorizacionGasto", b =>
                {
                    b.Property<int>("IdAutorizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_autorizacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAutorizacion"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion")
                        .HasComment("Niveles de firma para gastos");

                    b.HasKey("IdAutorizacion")
                        .HasName("PRIMARY");

                    b.ToTable("autorizacion_gasto", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.Egreso", b =>
                {
                    b.Property<int>("IdEgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_egreso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEgreso"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("concepto");

                    b.Property<DateTime?>("FechaEgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_egreso")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdAutorizacion")
                        .HasColumnType("int")
                        .HasColumnName("id_autorizacion");

                    b.Property<int>("IdBancoOrigen")
                        .HasColumnType("int")
                        .HasColumnName("id_banco_origen");

                    b.Property<int>("IdCondominio")
                        .HasColumnType("int")
                        .HasColumnName("id_condominio");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int")
                        .HasColumnName("id_forma_pago");

                    b.Property<int?>("IdPersonaBeneficiario")
                        .HasColumnType("int")
                        .HasColumnName("id_persona_beneficiario")
                        .HasComment("Opcional");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor")
                        .HasComment("Opcional");

                    b.Property<int>("IdUsuarioRegistro")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_registro");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_total");

                    b.Property<string>("NroFacturaProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nro_factura_proveedor");

                    b.HasKey("IdEgreso")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAutorizacion" }, "fk_egreso_aut");

                    b.HasIndex(new[] { "IdBancoOrigen" }, "fk_egreso_banco");

                    b.HasIndex(new[] { "IdCondominio" }, "fk_egreso_condominio");

                    b.HasIndex(new[] { "IdFormaPago" }, "fk_egreso_fp");

                    b.HasIndex(new[] { "IdPersonaBeneficiario" }, "fk_egreso_persona");

                    b.HasIndex(new[] { "IdProveedor" }, "fk_egreso_proveedor");

                    b.HasIndex(new[] { "IdUsuarioRegistro" }, "fk_egreso_usuario");

                    b.ToTable("egreso", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.EgresoDetalle", b =>
                {
                    b.Property<int>("IdEgresoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_egreso_detalle");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEgresoDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("concepto");

                    b.Property<int>("IdEgreso")
                        .HasColumnType("int")
                        .HasColumnName("id_egreso");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdEgresoDetalle")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEgreso" }, "fk_egreso_detalle_egreso");

                    b.ToTable("egreso_detalle", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.ExpenseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EgresoId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EgresoId");

                    b.ToTable("ExpenseAttachments", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.PlanCuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCuenta"));

                    b.Property<string>("CodigoCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo_cuenta")
                        .HasComment("Ej: 1.1.01");

                    b.Property<bool?>("EsImputable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_imputable")
                        .HasDefaultValueSql("'1'")
                        .HasComment("Si/No");

                    b.Property<int?>("IdCuentaPadre")
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta_padre")
                        .HasComment("Recursiva");

                    b.Property<int?>("NivelJerarquia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nivel_jerarquia")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCuenta")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCuentaPadre" }, "fk_pc_padre");

                    b.ToTable("plan_cuentas", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.CatalogoServicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_servicio")
                        .HasComment("Antes: serviciopago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<decimal?>("CostoBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo_base")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<bool?>("EsRecurrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_recurrente")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre")
                        .HasComment("Agua, Luz, Multa, Expensa");

                    b.HasKey("IdServicio")
                        .HasName("PRIMARY");

                    b.ToTable("catalogo_servicio", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Vigente'")
                        .HasComment("Vigente, Finalizado, Rescindido");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly?>("FechaFirma")
                        .HasColumnType("date")
                        .HasColumnName("fecha_firma");

                    b.Property<DateOnly?>("FechaIngresoReal")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso_real");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdPropiedad")
                        .HasColumnType("int")
                        .HasColumnName("id_propiedad");

                    b.Property<int?>("IdUsuarioCreador")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_creador");

                    b.Property<decimal>("MontoExpensaPactada")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_expensa_pactada");

                    b.Property<string>("MotivoBaja")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motivo_baja");

                    b.HasKey("IdContrato")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuarioCreador" }, "fk_contrato_creador");

                    b.HasIndex(new[] { "IdPropiedad" }, "fk_contrato_propiedad");

                    b.ToTable("contrato", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.ContratoParticipante", b =>
                {
                    b.Property<int>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateOnly?>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("RolContrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rol_contrato")
                        .HasComment("Titular, Inquilino, Garante");

                    b.HasKey("IdContrato", "IdPersona")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdPersona" }, "fk_cp_persona");

                    b.ToTable("contrato_participante", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.ContratoServicioSuscrito", b =>
                {
                    b.Property<int>("IdSuscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_suscripcion")
                        .HasComment("Antes: servicio_contrato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSuscripcion"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<decimal?>("CostoPersonalizado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo_personalizado")
                        .HasComment("Si difiere del base");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.HasKey("IdSuscripcion")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdContrato" }, "fk_css_contrato");

                    b.HasIndex(new[] { "IdServicio" }, "fk_css_servicio");

                    b.ToTable("contrato_servicio_suscrito", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.LecturaServicio", b =>
                {
                    b.Property<int>("IdLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_lectura");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLectura"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<DateOnly?>("FechaLectura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_lectura");

                    b.Property<int>("IdSuscripcion")
                        .HasColumnType("int")
                        .HasColumnName("id_suscripcion");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("mes");

                    b.Property<decimal>("MontoCalculado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_calculado");

                    b.Property<decimal?>("ValorLeido")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor_leido")
                        .HasComment("Para agua/luz variable");

                    b.HasKey("IdLectura")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdSuscripcion" }, "fk_lectura_suscripcion");

                    b.ToTable("lectura_servicio", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.ConfigAvisoCobranza", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_config")
                        .HasComment("Antes: confaviso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdConfig"));

                    b.Property<int?>("DiasVencimientoDefecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dias_vencimiento_defecto")
                        .HasDefaultValueSql("'10'");

                    b.Property<int>("IdCondominio")
                        .HasColumnType("int")
                        .HasColumnName("id_condominio");

                    b.Property<string>("TextoFooter")
                        .HasColumnType("text")
                        .HasColumnName("texto_footer");

                    b.Property<string>("TextoHeader")
                        .HasColumnType("text")
                        .HasColumnName("texto_header");

                    b.HasKey("IdConfig")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCondominio" }, "fk_aviso_condominio");

                    b.ToTable("config_aviso_cobranza", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.DeudaCabecera", b =>
                {
                    b.Property<int>("IdDeuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_deuda");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDeuda"));

                    b.Property<int>("AnioPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("anio_periodo");

                    b.Property<string>("EstadoPago")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_pago")
                        .HasDefaultValueSql("'PENDIENTE'")
                        .HasComment("PENDIENTE, PARCIAL, PAGADO, ANULADO");

                    b.Property<DateOnly?>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    b.Property<int?>("IdUsuarioGenerador")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_generador");

                    b.Property<int>("MesPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("mes_periodo");

                    b.Property<decimal?>("TotalDeuda")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_deuda")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("TotalPagado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_pagado")
                        .HasDefaultValueSql("'0.00'");

                    b.HasKey("IdDeuda")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdContrato" }, "fk_deuda_contrato");

                    b.HasIndex(new[] { "IdUsuarioGenerador" }, "fk_deuda_usuario");

                    b.ToTable("deuda_cabecera", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.DeudaDetalle", b =>
                {
                    b.Property<int>("IdDeudaDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_deuda_det");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDeudaDet"));

                    b.Property<decimal?>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cantidad")
                        .HasDefaultValueSql("'1.00'");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("concepto")
                        .HasComment("Ej: Expensa Mayo 2025");

                    b.Property<int>("IdDeuda")
                        .HasColumnType("int")
                        .HasColumnName("id_deuda");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio")
                        .HasComment("Origen del cobro");

                    b.Property<decimal>("MontoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_unitario");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("IdDeudaDet")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdDeuda" }, "fk_dd_cabecera");

                    b.HasIndex(new[] { "IdServicio" }, "fk_dd_servicio");

                    b.ToTable("deuda_detalle", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.FormaPago", b =>
                {
                    b.Property<int>("IdFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_forma_pago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFormaPago"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion")
                        .HasComment("Efectivo, Cheque, Transferencia");

                    b.Property<int?>("IdCuentaContableAsociada")
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta_contable_asociada");

                    b.HasKey("IdFormaPago")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCuentaContableAsociada" }, "fk_fp_cuenta");

                    b.ToTable("forma_pago", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.TransaccionPago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago")
                        .HasComment("Antes: cuota");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'CONFIRMADO'")
                        .HasComment("CONFIRMADO, RECHAZADO");

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaRecibo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_recibo");

                    b.Property<int>("IdBancoDestino")
                        .HasColumnType("int")
                        .HasColumnName("id_banco_destino");

                    b.Property<int>("IdDeuda")
                        .HasColumnType("int")
                        .HasColumnName("id_deuda")
                        .HasComment("Pago especifico de una deuda");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int")
                        .HasColumnName("id_forma_pago");

                    b.Property<int>("IdPersonaPagador")
                        .HasColumnType("int")
                        .HasColumnName("id_persona_pagador");

                    b.Property<decimal>("MontoAbonado")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_abonado");

                    b.Property<string>("NroComprobanteBanco")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nro_comprobante_banco");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("ReciboUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("recibo_url");

                    b.Property<decimal?>("TipoCambio")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("tipo_cambio")
                        .HasDefaultValueSql("'1.0000'");

                    b.HasKey("IdPago")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdBancoDestino" }, "fk_tp_banco");

                    b.HasIndex(new[] { "IdDeuda" }, "fk_tp_deuda");

                    b.HasIndex(new[] { "IdFormaPago" }, "fk_tp_forma");

                    b.HasIndex(new[] { "IdPersonaPagador" }, "fk_tp_persona");

                    b.ToTable("transaccion_pago", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Financiero.ChargeConcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int")
                        .HasColumnName("condominium_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_recurrent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.ToTable("charge_concept", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Financiero.FinancialConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominiumId")
                        .HasColumnType("int")
                        .HasColumnName("condominium_id");

                    b.Property<int>("GraceDays")
                        .HasColumnType("int")
                        .HasColumnName("grace_days");

                    b.Property<decimal>("MonthlyInterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("monthly_interest_rate");

                    b.HasKey("Id");

                    b.HasIndex("CondominiumId");

                    b.ToTable("financial_config", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.Banco", b =>
                {
                    b.Property<int>("IdBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_banco");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBanco"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("IdCuentaContableAsociada")
                        .HasColumnType("int")
                        .HasColumnName("id_cuenta_contable_asociada");

                    b.Property<string>("Moneda")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("moneda")
                        .HasDefaultValueSql("'BOB'");

                    b.Property<string>("NombreEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_entidad");

                    b.Property<string>("NumeroCuenta")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_cuenta");

                    b.Property<decimal>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("BANCO")
                        .HasColumnName("tipo");

                    b.HasKey("IdBanco")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCuentaContableAsociada" }, "fk_banco_cuenta");

                    b.ToTable("banco", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.MedioContacto", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contacto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdContacto"));

                    b.Property<bool?>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_principal")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo")
                        .HasComment("Telefono, Celular, Email, Facebook");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("valor")
                        .HasComment("El numero o correo");

                    b.HasKey("IdContacto")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPersona" }, "fk_contacto_persona");

                    b.ToTable("medio_contacto", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Ci")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ci");

                    b.Property<bool?>("EsActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_civil");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int?>("IdFamiliarResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_familiar_responsable")
                        .HasComment("Recursiva: Para hijos/dependientes");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_completo")
                        .HasComment("Antes: nombre");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("sexo")
                        .IsFixedLength();

                    b.HasKey("IdPersona")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdFamiliarResponsable" }, "fk_persona_familiar");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nit")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nit");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("razon_social");

                    b.HasKey("IdProveedor")
                        .HasName("PRIMARY");

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Condominio", b =>
                {
                    b.Property<int>("IdCondominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_condominio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCondominio"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("ConfigDiaCobro")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("config_dia_cobro");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<int>("IdAdminPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_admin_persona");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("logo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("SuperficieTotalM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("superficie_total_m2");

                    b.HasKey("IdCondominio")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAdminPersona" }, "fk_condominio_admin");

                    b.ToTable("condominio", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Manzano", b =>
                {
                    b.Property<int>("IdManzano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_manzano");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdManzano"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("IdCondominio")
                        .HasColumnType("int")
                        .HasColumnName("id_condominio");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdManzano")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCondominio" }, "fk_manzano_condominio");

                    b.ToTable("manzano", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Propiedad", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_propiedad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPropiedad"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("CodigoUnidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo_unidad");

                    b.Property<decimal?>("ExpensaBaseDefecto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("expensa_base_defecto");

                    b.Property<int>("IdManzano")
                        .HasColumnType("int")
                        .HasColumnName("id_manzano");

                    b.Property<string>("NombreFuncional")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_funcional");

                    b.Property<decimal?>("PorcentajeParticipacion")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("porcentaje_participacion")
                        .HasComment("Para prorrateo");

                    b.Property<decimal>("SaldoAFavor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("saldo_a_favor")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal>("SaldoDeudor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("saldo_deudor")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("SuperficieM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("superficie_m2");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo")
                        .HasComment("Casa, Depto, Lote");

                    b.HasKey("IdPropiedad")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdManzano" }, "fk_propiedad_manzano");

                    b.ToTable("propiedad", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.CondominioMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionString")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("CondominiosMaster");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.PermisoMaster", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdPermiso");

                    b.ToTable("PermisosMaster");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.RolMaster", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("RolesMaster");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.UsuarioCondominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondominioId")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.HasIndex("IdRol");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioCondominio");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.UsuarioMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EsSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdRolPrincipal")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdRolPrincipal");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UsuariosMaster");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Reservas.RecursoComun", b =>
                {
                    b.Property<int>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRecurso"));

                    b.Property<string>("ColorCalendario")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color_calendario")
                        .HasComment("Antes en tabla evento");

                    b.Property<decimal?>("CostoGarantia")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo_garantia")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("CostoReserva")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo_reserva")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int>("IdCondominio")
                        .HasColumnType("int")
                        .HasColumnName("id_condominio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre")
                        .HasComment("Churrasquera, Salon");

                    b.HasKey("IdRecurso")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCondominio" }, "fk_recurso_condominio");

                    b.ToTable("recurso_comun", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Reservas.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reserva")
                        .HasComment("Antes: evento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("AmenizadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("amenizado_por");

                    b.Property<int?>("CantidadInvitados")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_invitados");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'PENDIENTE'")
                        .HasComment("PENDIENTE, CONFIRMADA, FINALIZADA");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato")
                        .HasComment("Quien reserva");

                    b.Property<int>("IdRecurso")
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    b.Property<decimal?>("MontoTotalCobrado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_total_cobrado");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("motivo");

                    b.HasKey("IdReserva")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdContrato" }, "fk_reserva_contrato");

                    b.HasIndex(new[] { "IdRecurso" }, "fk_reserva_recurso");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("EstaHabilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("esta_habilitado")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("id_persona");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash")
                        .HasComment("Antes: contrasena");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPersona" }, "fk_usuario_persona");

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("PermisoMasterRolMaster", b =>
                {
                    b.Property<int>("PermisosIdPermiso")
                        .HasColumnType("int");

                    b.Property<int>("RolesIdRol")
                        .HasColumnType("int");

                    b.HasKey("PermisosIdPermiso", "RolesIdRol");

                    b.HasIndex("RolesIdRol");

                    b.ToTable("PermisoMasterRolMaster");
                });

            modelBuilder.Entity("ConfigContableServicio", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.PlanCuenta", null)
                        .WithMany()
                        .HasForeignKey("IdCuentaIngreso")
                        .IsRequired()
                        .HasConstraintName("fk_ccs_cuenta");

                    b.HasOne("Consulcon.Domain.Entities.Contratos.CatalogoServicio", null)
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("fk_ccs_servicio");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Comunicacion.ComunicadoBlog", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Condominio", "IdCondominioNavigation")
                        .WithMany("ComunicadoBlogs")
                        .HasForeignKey("IdCondominio")
                        .IsRequired()
                        .HasConstraintName("fk_blog_condominio");

                    b.Navigation("IdCondominioNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AccountDailyBalance", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.General.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoIdBanco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AccountTransactionHistory", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.General.Banco", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.Egreso", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AsientoContable", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Condominio", "IdCondominioNavigation")
                        .WithMany("AsientoContables")
                        .HasForeignKey("IdCondominio")
                        .IsRequired()
                        .HasConstraintName("fk_asiento_condominio");

                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.Egreso", "IdTransaccionOrigenEgresoNavigation")
                        .WithMany("AsientoContables")
                        .HasForeignKey("IdTransaccionOrigenEgreso")
                        .HasConstraintName("fk_asiento_egreso");

                    b.HasOne("Consulcon.Domain.Entities.Facturacion.TransaccionPago", "IdTransaccionOrigenPagoNavigation")
                        .WithMany("AsientoContables")
                        .HasForeignKey("IdTransaccionOrigenPago")
                        .HasConstraintName("fk_asiento_pago");

                    b.Navigation("IdCondominioNavigation");

                    b.Navigation("IdTransaccionOrigenEgresoNavigation");

                    b.Navigation("IdTransaccionOrigenPagoNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AsientoDetalle", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.AsientoContable", "IdAsientoNavigation")
                        .WithMany("AsientoDetalles")
                        .HasForeignKey("IdAsiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ad_asiento");

                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.PlanCuenta", "IdCuentaNavigation")
                        .WithMany("AsientoDetalles")
                        .HasForeignKey("IdCuenta")
                        .IsRequired()
                        .HasConstraintName("fk_ad_cuenta");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdCuentaNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.Egreso", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.AutorizacionGasto", "IdAutorizacionNavigation")
                        .WithMany("Egresos")
                        .HasForeignKey("IdAutorizacion")
                        .IsRequired()
                        .HasConstraintName("fk_egreso_aut");

                    b.HasOne("Consulcon.Domain.Entities.General.Banco", "IdBancoOrigenNavigation")
                        .WithMany("Egresos")
                        .HasForeignKey("IdBancoOrigen")
                        .IsRequired()
                        .HasConstraintName("fk_egreso_banco");

                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Condominio", "IdCondominioNavigation")
                        .WithMany("Egresos")
                        .HasForeignKey("IdCondominio")
                        .IsRequired()
                        .HasConstraintName("fk_egreso_condominio");

                    b.HasOne("Consulcon.Domain.Entities.Facturacion.FormaPago", "IdFormaPagoNavigation")
                        .WithMany("Egresos")
                        .HasForeignKey("IdFormaPago")
                        .IsRequired()
                        .HasConstraintName("fk_egreso_fp");

                    b.HasOne("Consulcon.Domain.Entities.General.Persona", "IdPersonaBeneficiarioNavigation")
                        .WithMany("Egresos")
                        .HasForeignKey("IdPersonaBeneficiario")
                        .HasConstraintName("fk_egreso_persona");

                    b.HasOne("Consulcon.Domain.Entities.General.Proveedor", "IdProveedorNavigation")
                        .WithMany("Egresos")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("fk_egreso_proveedor");

                    b.HasOne("Consulcon.Domain.Entities.Seguridad.Usuario", "IdUsuarioRegistroNavigation")
                        .WithMany("Egresos")
                        .HasForeignKey("IdUsuarioRegistro")
                        .IsRequired()
                        .HasConstraintName("fk_egreso_usuario");

                    b.Navigation("IdAutorizacionNavigation");

                    b.Navigation("IdBancoOrigenNavigation");

                    b.Navigation("IdCondominioNavigation");

                    b.Navigation("IdFormaPagoNavigation");

                    b.Navigation("IdPersonaBeneficiarioNavigation");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdUsuarioRegistroNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.EgresoDetalle", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.Egreso", "IdEgresoNavigation")
                        .WithMany("EgresoDetalles")
                        .HasForeignKey("IdEgreso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_egreso_detalle_egreso");

                    b.Navigation("IdEgresoNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.ExpenseAttachment", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.Egreso", "Egreso")
                        .WithMany("Attachments")
                        .HasForeignKey("EgresoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egreso");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.PlanCuenta", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.PlanCuenta", "IdCuentaPadreNavigation")
                        .WithMany("InverseIdCuentaPadreNavigation")
                        .HasForeignKey("IdCuentaPadre")
                        .HasConstraintName("fk_pc_padre");

                    b.Navigation("IdCuentaPadreNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.Contrato", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Propiedad", "IdPropiedadNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdPropiedad")
                        .IsRequired()
                        .HasConstraintName("fk_contrato_propiedad");

                    b.HasOne("Consulcon.Domain.Entities.Seguridad.Usuario", "IdUsuarioCreadorNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdUsuarioCreador")
                        .HasConstraintName("fk_contrato_creador");

                    b.Navigation("IdPropiedadNavigation");

                    b.Navigation("IdUsuarioCreadorNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.ContratoParticipante", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contratos.Contrato", "IdContratoNavigation")
                        .WithMany("ContratoParticipantes")
                        .HasForeignKey("IdContrato")
                        .IsRequired()
                        .HasConstraintName("fk_cp_contrato");

                    b.HasOne("Consulcon.Domain.Entities.General.Persona", "IdPersonaNavigation")
                        .WithMany("ContratoParticipantes")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("fk_cp_persona");

                    b.Navigation("IdContratoNavigation");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.ContratoServicioSuscrito", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contratos.Contrato", "IdContratoNavigation")
                        .WithMany("ContratoServicioSuscritos")
                        .HasForeignKey("IdContrato")
                        .IsRequired()
                        .HasConstraintName("fk_css_contrato");

                    b.HasOne("Consulcon.Domain.Entities.Contratos.CatalogoServicio", "IdServicioNavigation")
                        .WithMany("ContratoServicioSuscritos")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("fk_css_servicio");

                    b.Navigation("IdContratoNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.LecturaServicio", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contratos.ContratoServicioSuscrito", "IdSuscripcionNavigation")
                        .WithMany("LecturaServicios")
                        .HasForeignKey("IdSuscripcion")
                        .IsRequired()
                        .HasConstraintName("fk_lectura_suscripcion");

                    b.Navigation("IdSuscripcionNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.ConfigAvisoCobranza", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Condominio", "IdCondominioNavigation")
                        .WithMany("ConfigAvisoCobranzas")
                        .HasForeignKey("IdCondominio")
                        .IsRequired()
                        .HasConstraintName("fk_aviso_condominio");

                    b.Navigation("IdCondominioNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.DeudaCabecera", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contratos.Contrato", "IdContratoNavigation")
                        .WithMany("DeudaCabeceras")
                        .HasForeignKey("IdContrato")
                        .IsRequired()
                        .HasConstraintName("fk_deuda_contrato");

                    b.HasOne("Consulcon.Domain.Entities.Seguridad.Usuario", "IdUsuarioGeneradorNavigation")
                        .WithMany("DeudaCabeceras")
                        .HasForeignKey("IdUsuarioGenerador")
                        .HasConstraintName("fk_deuda_usuario");

                    b.Navigation("IdContratoNavigation");

                    b.Navigation("IdUsuarioGeneradorNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.DeudaDetalle", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Facturacion.DeudaCabecera", "IdDeudaNavigation")
                        .WithMany("DeudaDetalles")
                        .HasForeignKey("IdDeuda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dd_cabecera");

                    b.HasOne("Consulcon.Domain.Entities.Contratos.CatalogoServicio", "IdServicioNavigation")
                        .WithMany("DeudaDetalles")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("fk_dd_servicio");

                    b.Navigation("IdDeudaNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.FormaPago", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.PlanCuenta", "IdCuentaContableAsociadaNavigation")
                        .WithMany("FormaPagos")
                        .HasForeignKey("IdCuentaContableAsociada")
                        .HasConstraintName("fk_fp_cuenta");

                    b.Navigation("IdCuentaContableAsociadaNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.TransaccionPago", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.General.Banco", "IdBancoDestinoNavigation")
                        .WithMany("TransaccionPagos")
                        .HasForeignKey("IdBancoDestino")
                        .IsRequired()
                        .HasConstraintName("fk_tp_banco");

                    b.HasOne("Consulcon.Domain.Entities.Facturacion.DeudaCabecera", "IdDeudaNavigation")
                        .WithMany("TransaccionPagos")
                        .HasForeignKey("IdDeuda")
                        .IsRequired()
                        .HasConstraintName("fk_tp_deuda");

                    b.HasOne("Consulcon.Domain.Entities.Facturacion.FormaPago", "IdFormaPagoNavigation")
                        .WithMany("TransaccionPagos")
                        .HasForeignKey("IdFormaPago")
                        .IsRequired()
                        .HasConstraintName("fk_tp_forma");

                    b.HasOne("Consulcon.Domain.Entities.General.Persona", "IdPersonaPagadorNavigation")
                        .WithMany("TransaccionPagos")
                        .HasForeignKey("IdPersonaPagador")
                        .IsRequired()
                        .HasConstraintName("fk_tp_persona");

                    b.Navigation("IdBancoDestinoNavigation");

                    b.Navigation("IdDeudaNavigation");

                    b.Navigation("IdFormaPagoNavigation");

                    b.Navigation("IdPersonaPagadorNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Financiero.ChargeConcept", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Condominio", "Condominium")
                        .WithMany()
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Financiero.FinancialConfig", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Condominio", "Condominium")
                        .WithMany()
                        .HasForeignKey("CondominiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominium");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.Banco", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contabilidad.PlanCuenta", "IdCuentaContableAsociadaNavigation")
                        .WithMany("Bancos")
                        .HasForeignKey("IdCuentaContableAsociada")
                        .HasConstraintName("fk_banco_cuenta");

                    b.Navigation("IdCuentaContableAsociadaNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.MedioContacto", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.General.Persona", "IdPersonaNavigation")
                        .WithMany("MedioContactos")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contacto_persona");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.Persona", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.General.Persona", "IdFamiliarResponsableNavigation")
                        .WithMany("InverseIdFamiliarResponsableNavigation")
                        .HasForeignKey("IdFamiliarResponsable")
                        .HasConstraintName("fk_persona_familiar");

                    b.Navigation("IdFamiliarResponsableNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Condominio", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.General.Persona", "IdAdminPersonaNavigation")
                        .WithMany("Condominios")
                        .HasForeignKey("IdAdminPersona")
                        .IsRequired()
                        .HasConstraintName("fk_condominio_admin");

                    b.Navigation("IdAdminPersonaNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Manzano", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Condominio", "IdCondominioNavigation")
                        .WithMany("Manzanos")
                        .HasForeignKey("IdCondominio")
                        .IsRequired()
                        .HasConstraintName("fk_manzano_condominio");

                    b.Navigation("IdCondominioNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Propiedad", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Manzano", "IdManzanoNavigation")
                        .WithMany("Propiedads")
                        .HasForeignKey("IdManzano")
                        .IsRequired()
                        .HasConstraintName("fk_propiedad_manzano");

                    b.Navigation("IdManzanoNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.UsuarioCondominio", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Master.CondominioMaster", "Condominio")
                        .WithMany("Usuarios")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consulcon.Domain.Entities.Master.RolMaster", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consulcon.Domain.Entities.Master.UsuarioMaster", "Usuario")
                        .WithMany("Condominios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.UsuarioMaster", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Master.RolMaster", "RolPrincipal")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRolPrincipal");

                    b.Navigation("RolPrincipal");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Reservas.RecursoComun", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Inmuebles.Condominio", "IdCondominioNavigation")
                        .WithMany("RecursoComuns")
                        .HasForeignKey("IdCondominio")
                        .IsRequired()
                        .HasConstraintName("fk_recurso_condominio");

                    b.Navigation("IdCondominioNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Reservas.Reserva", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Contratos.Contrato", "IdContratoNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdContrato")
                        .IsRequired()
                        .HasConstraintName("fk_reserva_contrato");

                    b.HasOne("Consulcon.Domain.Entities.Reservas.RecursoComun", "IdRecursoNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdRecurso")
                        .IsRequired()
                        .HasConstraintName("fk_reserva_recurso");

                    b.Navigation("IdContratoNavigation");

                    b.Navigation("IdRecursoNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.General.Persona", "IdPersonaNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("fk_usuario_persona");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("PermisoMasterRolMaster", b =>
                {
                    b.HasOne("Consulcon.Domain.Entities.Master.PermisoMaster", null)
                        .WithMany()
                        .HasForeignKey("PermisosIdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consulcon.Domain.Entities.Master.RolMaster", null)
                        .WithMany()
                        .HasForeignKey("RolesIdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AsientoContable", b =>
                {
                    b.Navigation("AsientoDetalles");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.AutorizacionGasto", b =>
                {
                    b.Navigation("Egresos");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.Egreso", b =>
                {
                    b.Navigation("AsientoContables");

                    b.Navigation("Attachments");

                    b.Navigation("EgresoDetalles");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contabilidad.PlanCuenta", b =>
                {
                    b.Navigation("AsientoDetalles");

                    b.Navigation("Bancos");

                    b.Navigation("FormaPagos");

                    b.Navigation("InverseIdCuentaPadreNavigation");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.CatalogoServicio", b =>
                {
                    b.Navigation("ContratoServicioSuscritos");

                    b.Navigation("DeudaDetalles");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.Contrato", b =>
                {
                    b.Navigation("ContratoParticipantes");

                    b.Navigation("ContratoServicioSuscritos");

                    b.Navigation("DeudaCabeceras");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Contratos.ContratoServicioSuscrito", b =>
                {
                    b.Navigation("LecturaServicios");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.DeudaCabecera", b =>
                {
                    b.Navigation("DeudaDetalles");

                    b.Navigation("TransaccionPagos");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.FormaPago", b =>
                {
                    b.Navigation("Egresos");

                    b.Navigation("TransaccionPagos");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Facturacion.TransaccionPago", b =>
                {
                    b.Navigation("AsientoContables");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.Banco", b =>
                {
                    b.Navigation("Egresos");

                    b.Navigation("TransaccionPagos");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.Persona", b =>
                {
                    b.Navigation("Condominios");

                    b.Navigation("ContratoParticipantes");

                    b.Navigation("Egresos");

                    b.Navigation("InverseIdFamiliarResponsableNavigation");

                    b.Navigation("MedioContactos");

                    b.Navigation("TransaccionPagos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.General.Proveedor", b =>
                {
                    b.Navigation("Egresos");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Condominio", b =>
                {
                    b.Navigation("AsientoContables");

                    b.Navigation("ComunicadoBlogs");

                    b.Navigation("ConfigAvisoCobranzas");

                    b.Navigation("Egresos");

                    b.Navigation("Manzanos");

                    b.Navigation("RecursoComuns");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Manzano", b =>
                {
                    b.Navigation("Propiedads");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Inmuebles.Propiedad", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.CondominioMaster", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.RolMaster", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Master.UsuarioMaster", b =>
                {
                    b.Navigation("Condominios");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Reservas.RecursoComun", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Consulcon.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("DeudaCabeceras");

                    b.Navigation("Egresos");
                });
#pragma warning restore 612, 618
        }
    }
}
