<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3cab2221-6cf7-49e2-b4a5-22bfe3667b1c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Consulcon.Application\Consulcon.Application.csproj" />
    <ProjectReference Include="..\Consulcon.Infrastructure\Consulcon.Infrastructure.csproj" />
    <ProjectReference Include="..\Consulcon.Domain\Consulcon.Domain.csproj" />
  </ItemGroup>

</Project>
